Group full detector mark
dream-team-karmiel/project-x pull request #15
Opened 2023-12-14 17:48 UTC by MarkKlotsman

full detector module with unit tests

2023-12-15 09:05 UTC, PavelDubovik requested changes
Привет! В целом все отлично! Давай поправим несколько моментов и тогда будем мерить, ок? Главное не забудь убрать пароль от  MongoDB и я бы поменял его, чтобы никто не мог им воспользоваться.

2023-12-15 09:05 UTC, PavelDubovik commented on group-full-detector/src/test/resources/application.properties
> +spring.data.mongodb.uri=mongodb+srv://root:SPbAEP@cluster0.yzfgyl2.mongodb.net/ordersData?retryWrites=true&w=majority
Вот такие вещи точно лучше выносить в переменные среды, чтобы они не появлялись на GitHub

2023-12-15 16:32 UTC, MarkKlotsman commented on group-full-detector/src/main/java/com/karmiel/groupfulldetector/GroupFullDetectorApp.java
> +@EnableMongoRepositories
согасен. Spring сам просканирует пакет. Явного указания не трубуется. Удалю.

2023-12-15 16:36 UTC, MarkKlotsman commented on group-full-detector/src/main/java/com/karmiel/groupfulldetector/service/FullDetectorImpl.java
> +    @Value("close-order")
согласен. не вычистил код, с прошлой реализации осталось. удалю

2023-12-15 16:37 UTC, MarkKlotsman commented on group-full-detector/src/main/java/com/karmiel/groupfulldetector/service/FullDetectorImpl.java
> +        return orderData.map(OrderData::getId).orElse(null);
спасибо tips в IDEA :))

2023-12-15 16:48 UTC, MarkKlotsman commented on group-full-detector/src/main/java/com/karmiel/groupfulldetector/service/FullDetectorKafka.java
> +    String closeOrderTopic = "close-order";
все верно. переделал через аннотацию @Value, что бы тянуть из application.properties

2023-12-15 16:49 UTC, MarkKlotsman commented on group-full-detector/src/main/resources/application.properties
> +spring.cloud.stream.bindings.receiveFullData-in-0.destination=${KAFKA_CHECK_ORDER}
хорошо. дефольтные значения есть, так что оставлю без изменений

2023-12-15 16:58 UTC, MarkKlotsman commented on group-full-detector/src/test/resources/application.properties
> +spring.data.mongodb.uri=mongodb+srv://root:SPbAEP@cluster0.yzfgyl2.mongodb.net/ordersData?retryWrites=true&w=majority
my bad. вынес в переменные среды

2023-12-16 17:09 UTC, PavelDubovik approved these changes
На мой взгляд все отлично! Я оставил только один маленький комментарий касательно нейминга. Можешь оставить и мержить, а можешь заменить и уже тогда мержить. К завтрашнему дню нужно подготовить задачи, которые нам нужно выполнить по проекту и выбать для себя ту, которой хотелось бы заниматься. 
Хорошего вечера!

2023-12-16 17:09 UTC, PavelDubovik commented on group-full-detector/src/main/java/com/karmiel/groupfulldetector/service/FullDetectorKafka.java
> +    FullDetectorImpl impl;
Может имеет смысл изменить имя переменной.

Я бы сделал так:
Имена для интерфейса сделал бы как у тебя или так: FullDetectorService и FullDetectorServiceImpl. А вот переменную назвал бы service или fullDetectorService. На мой взгляд, так будет понятнее, когда встречаешь переменную в коде дальше. 

Понятно, что это не ошибка, но это поможет людям, которые читают твой код легче в нем разобраться.

2023-12-17 10:22 UTC, merged