Close record service alexey zak
dream-team-karmiel/project-x pull request #16
Opened 2023-12-15 08:23 UTC by naje1

2023-12-15 09:46 UTC, morozofAlexey submitted a review, later dismissed
Entity поменялись, последняя версия есть на схеме, оставил комментарий что нужно поменять.
В остальном чисто косметические замечания.

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/entities/Order.java
> +    String orderStatus;
Поле OrderStatus это должен быть enum:
public enum OrderStatus {
NEW, CONFIRMED, CANCELLED, DONE
}

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/entities/Order.java
> +
Т.к. это entity для работы с БД то нужно указать аннотации
@Document(collection = "orders")
@Data

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/entities/Order.java
> +
Тут нужна аннотация @Id которая показывает что поле id будет primary key в базе данных

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/CloseRecordServiceAppl.java
> +@SpringBootApplication
@SpringBootApplication - аннотация тут не нужна, она используется только а аппликационном классе где main

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/CloseRecordServiceAppl.java
> +        SpringApplication.run(CloseRecordServiceAppl.class);
Метод main тут не нужен, у тебя уже есть класс с main (CloseRecordService.java)

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/main/java/com/karmiel/close/record/service/CloseRecordServiceAppl.java
> +Consumer<CloseRecordDto> orderDtoConsumer(){
Для данного метода нужно добавить в файл application.properties настройку binding в которой будет указано имя топика (Environment variables есть на картинке с нашей архитектурой). И там же нужно добавить настройку группы, без этого не будет работать с реальной кафкой

2023-12-15 09:46 UTC, morozofAlexey commented on close-record-service/src/test/java/com/karmiel/close/record/service/CloseRecordServiceTest.java
> +//        assertEquals(EXPECTED_STATUS,updateOrder.getOrderStatus());
Закоментированный код надо убрать

2023-12-15 09:53 UTC, morozofAlexey requested changes
Entity поменялись, последняя версия есть на схеме, оставил комментарий что нужно поменять.
В остальном чисто косметические замечания.

2023-12-15 22:15 UTC, naje1 commented on close-record-service/src/main/java/com/karmiel/close/record/service/CloseRecordServiceAppl.java
> +        SpringApplication.run(CloseRecordServiceAppl.class);
класс CloseRecordService у меня отсутствует, у меня есть только класс  СloseRecordServiceAppl, не понимаю, возможно это на гите что-то не так подтянулось

2023-12-15 22:15 UTC, naje1 commented on close-record-service/src/main/java/com/karmiel/close/record/service/CloseRecordServiceAppl.java
> +@SpringBootApplication
класс CloseRecordService у меня отсутствует, у меня есть только класс  СloseRecordServiceAppl, не понимаю, возможно это на гите что-то не так подтянулось

2023-12-15 22:16 UTC, naje1 commented on close-record-service/src/main/java/com/karmiel/close/record/service/entities/Order.java
> +
done

2023-12-15 22:17 UTC, naje1 commented on close-record-service/src/main/java/com/karmiel/close/record/service/entities/Order.java
> +    String orderStatus;
done

2023-12-16 14:52 UTC, closed without merging

2023-12-16 14:53 UTC, morozofAlexey commented
Отменил pull request т.к. есть еще один