Group lack detector pavel
dream-team-karmiel/project-x pull request #4
Opened 2023-12-07 13:29 UTC by PavelDubovik

2023-12-07 14:35 UTC, PavelDubovik reviewed
В целом все хорошо, но пару моментов лучше подправить.

2023-12-07 14:35 UTC, PavelDubovik commented on group-lack-detector/src/main/java/com/karmiel/grouplackdetector/controller/GroupLackDetectorController.java
> +@Slf4j
Зачем нужна эта аннотация?

2023-12-08 13:23 UTC, morozofAlexey requested changes

2023-12-08 13:23 UTC, morozofAlexey commented on group-lack-detector/src/test/java/com/karmiel/grouplackdetector/GroupLackDetectorTest.java
> +        pack.setId(1L);
1L - it's 1 liter? :)

2023-12-08 13:23 UTC, morozofAlexey commented on group-lack-detector/src/test/java/com/karmiel/grouplackdetector/GroupLackDetectorTest.java
> +        ObjectMapper mapper = new ObjectMapper();
It's better to declarate mapper one time on the top

2023-12-09 08:55 UTC, PavelDubovik commented on group-lack-detector/src/test/java/com/karmiel/grouplackdetector/GroupLackDetectorTest.java
> +        pack.setId(1L);
Нет. Id у  Measure типа Long :) 
Тут запрашивается объект с id = 1

2023-12-09 09:50 UTC, PavelDubovik commented on group-lack-detector/src/test/java/com/karmiel/grouplackdetector/GroupLackDetectorTest.java
> +        Container container = new Container();
У меня в классах entity стояла аннотация @Data от Lombok, а она не дает конструктор со всем полями. Переделал на @Getter, @Settter, @NoArgsConstructor и @AllArgsConstructor. Думаю, стоит ли добавить @EqualsAndHashCode. Ты как думаешь?

2023-12-09 10:26 UTC, morozofAlexey approved these changes
Everything's ok

2023-12-09 10:27 UTC, closed without merging