Data imitator
dream-team-karmiel/project-x pull request #8
Opened 2023-12-10 20:02 UTC by david-mirz

2023-12-10 22:52 UTC, PavelDubovik requested changes
В целом хорошо, но можно доработать логику снижения и увеличения наполненности контейнеров, чтобы генерировало заданное количество контейнеров и наполненность изменялась более логично. Если будет возможность распиши алгоритм действий имитатора на бумажке (или в миро можно нарисовать), и когда будет время, можем созвониться и обсудить.

2023-12-10 22:52 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            increaseQty(MIN_INCREASE, MAX_INCREASE);
Что я потерялся в логике кода.
Если у нас значение случайного контейнера меньше 10, то мы уходим в метод increaseQty и пытаемся увеличить произвольный контейнер на величину от 70 до 100. Если значение получается больше 100, то выходим с while, если меньше то остаемся на следующую итерацию и снова берем произвольный контейнер и пытаемся его увеличить.

2023-12-10 22:52 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +//        for (int i = 1; i <= N_MESSAGES; i++) {
Я правильно понимаю, что здесь сообщения отправляются пока значение не дойдет до 0?

2023-12-10 22:52 UTC, PavelDubovik commented on data-imitator/src/main/resources/application.properties
> +spring.kafka.bootstrap-servers=localhost:9092
Не уверен, что эта строчка нужна, т.к. 9092 порт по умолчанию для Кафки

2023-12-13 21:31 UTC, PavelDubovik requested changes
Привет! Теперь гораздо понятнее, но есть моменты, на которые нужно обратить внимание. Комментарии оставил по коду.

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/imitator/DataImitatorApp.java
> +package com.karmiel.data.container.imitator;
Не уверен, что такой вариант будет работать. Апликационный класс, чтобы сканировать все папки и находить бины, должен находиться в корне. Скорее всего в таком варианте апликационный класс ничего не найдет.

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +    private final int N_CONTAINERS = 5;
Так точно будет работать? Проверял?

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            while (!containersMap.containsKey(randomKey)) {
Тут будут лишние проходы. Вместо того чтобы за 5 проходов создать 5 контейнеров будет от 10 до 20 проходов. К тому же зачем нам рандомно генерировать имена контейнеров, когда мы знаем какие у них должны быть имена?

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +        while(true){
Может имеет смысл ограничить количество сообщений? Тем более что есть переменная N_MESSAGES

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            selectKey = keysList.get(randomInt(0, N_CONTAINERS));
Зачем здесь рандом? Может лучше сделать чтобы был проход по всем контейнером и каждый отправлял свое значение? Так будет более приближено к реальности (все датчики оправляют информацию раз через определенное время в какое-то время). Можно кстати поставить задержку по времени к примеру в секунду и тогда информация с датчиков будет отправлять раз в секунду.

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            res = temp < 0 ? 0 : temp;
Точно здесь temp может быть меньше 0?
value, chngAmnt и chngProb вроде не отрицательные

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +        } else if (value > 10 && value <= CONTAINER_THRESHOLD * 100) {
Чуть выше value сравнивается с CONTAINER_LOWEST * 100, а здесь с 10. Может лучше оставить один вариант?

2023-12-13 21:31 UTC, PavelDubovik commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            res = temp > 100 ? 100 : temp;
У нас же value не больше 100, как оно может после уменьшения стать больше 100?

2023-12-14 20:27 UTC, david-mirz commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            res = temp < 0 ? 0 : temp;
probably you are right, my logic was such that in case the next decrease would overthrow value below 0, so in this case a ternary would place it back to 0, same logic for over 100.

2023-12-14 20:31 UTC, david-mirz commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +        } else if (value > 10 && value <= CONTAINER_THRESHOLD * 100) {
line 91 checks for value < 10, line 97 checks value between 10 and 50... or did i confuse something?

2023-12-14 20:44 UTC, david-mirz commented on data-imitator/src/main/java/com/karmiel/data/container/service/DataGenerator.java
> +            res = temp > 100 ? 100 : temp;
не исключаю что что-то перепутал🤣

2023-12-20 07:29 UTC, PavelDubovik approved these changes

2023-12-20 07:29 UTC, merged